name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
api-version: 1.15
depend: [GriefPrevention, LuckPerms, Vault]
commands:
  bbb:
    description: Buy claimblocks
    usage: /bb (count)
  brb:
    description: Provide rankblocks
    usage: /brb (user) (count)
permissions:
  biemblocks.buyclaimblocks:
    description: Allows the user to buy claimblocks.
    default: false
